<?php echo $this->header_part; ?>

<form name="admin_form" id="admin_form" method="post" action="">
	
	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/admin/images/extensions.png">
			<?php echo $this->translate('Banners');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $this->cancel_url;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>

	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/admin/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a name');?>" value="<?php echo $this->name;?>" class="inputbox required" name="name" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Width');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/admin/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a width');?>" value="<?php echo $this->width;?>" class="inputbox required" name="width" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Height');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/admin/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a height');?>" value="<?php echo $this->height;?>" class="inputbox required" name="height" />
        		</td>
			</tr>
			
			<tr class="show_position" style="visibility:hidden;">
				<td width="150"><?php echo $this->translate('Position');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/admin/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a position');?>" value="<?php echo $this->position;?>" class="inputbox required" name="position" />
        		</td>
			</tr>
			
			<tr>
				<td width="150"><?php echo $this->translate('Code');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/admin/images/required.gif"></td>
				<td>
					<textarea style="width: 400px; height: 100px;" title="<?php echo $this->translate('Please enter a code');?>" class="inputbox required" name="html"><?php echo $this->html;?></textarea>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Page');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/admin/images/required.gif"></td>
				<td>
					<select name="controller_set">
						<?php foreach($this->controllers AS $k=>$v) { ?>
						<?php if($k == $this->controller_set) { ?>
						<option selected="selected" value="<?php echo $k;?>"><?php echo $v;?></option>
						<?php } else { ?>
						<option value="<?php echo $k;?>"><?php echo $v;?></option>
						<?php } ?>
						<?php } ?>
					</select>
        		</td>
			</tr>
			<?php if($this->categories) { ?>
			<tr class="show_cat" style="visibility:hidden;">
				<td width="150"><?php echo $this->translate('Category');?>: </td>
				<td class="holder-cat">
					<select name="category_id"> 
						<option value="0"><?php echo $this->translate('All');?></option>
						<?php foreach($this->categories as $cat) { ?>
						<option value="<?php echo $cat['category_id']; ?>" <?php if($this->category_id == $cat['category_id']) { ?>selected="selected"<?php } ?>><?php echo $cat['title'];?></option>
						<?php } ?>
					</select>	
				</td>
			</tr>
			<?php } ?>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>:</td>
				<td>
					<select name="status" class="select">
						<?php if($this->status) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Active');?></option>
						<option value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Active');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Status for Ajax Request');?>:</td>
				<td>
					<select name="status_in_js_mode" class="select">
						<?php if($this->status_in_js_mode) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Active');?></option>
						<option value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Active');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			
		</tbody>
	</table>
	
	
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $this->cancel_url;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('select[name=controller_set]').change(function() {
		if(this.value == 'category') {
			$('.show_cat').css("visibility","visible").show();
		} else {
			$('.show_cat').css("visibility","hidden").hide();
		}
		if(this.value == 'item') {
			$('.show_position').css("visibility","visible").show();
		} else {
			$('.show_position').css("visibility","hidden").hide();
		}
		var page = $('select[name=controller_set]').val();
		if(page != 'item') {
			if(<?php echo (int)Helper_Config::get('config_list_big_box');?>!=2) {
				$('input[name=width]').attr('readonly',true).val(470);
				$('input[name=height]').attr('readonly',true).val(641);
			} else {
				$('input[name=width]').attr('readonly',true).val(220);
				$('input[name=height]').attr('readonly',true).val(300);
			}
		} else {
			$('input[name=width]').attr('readonly',false).val(728);
			$('input[name=height]').attr('readonly',false).val(90);
		}
	}).change();
	
});
</script>

<?php echo $this->footer_part; ?>