<?php echo $this->header_part;   ?>
<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/admin/images/extensions.png">
		<?php echo $this->translate('Product Import and Export');?>
	</h3>
	<?php if($this->successfu_edite || $this->error_permision) { ?>
      <?php if($this->successfu_edite) { ?>
      <span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span>
            <?php echo $this->translate('Information was successfully changed!');?></span></span>
      <?php } else if($this->error_permision) { ?>
      <span id="fader" class="fleft mleft30"><span class="msgError"><span><?php echo $this->translate('Error!');?></span><?php echo $this->error_permision;?></span></span>
      <?php } ?>
      <script type="text/javascript"> 
      // <![CDATA[
      $(document).ready(function() {       
          setTimeout(function() {
              $("#fader").customFadeOut("slow" ,    
              function() {       
                  $("#fader").remove();  
              });
          },
          4000);
      });
      // ]]>
      </script>
      <?php } ?>
<!--
      <div class="fright mtop3">
   <a class="button" href="http://localhost/upload/admin/csvie/create"><?php echo $this->translate('Add new');?></a>
        <a class="button" href="javascript:void(0);" onclick="multiActionSelected('deleteMulti');"><?php echo $this->translate('Delete selected');?></a>
  
      </div>
-->     
 <div class="clear"></div>
  </div><p class="info">
      <?php echo $this->translate('Product Import-Export Manager');?>.<br>
   <!--	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
  -->
  </p>
   <?php
?>


	<form action="" method="post" enctype="multipart/form-data">
		<table cellpadding="0" cellspacing="0" border="0" class="table">
                 <tr>EXPORT CSV FILE :</tr>
			<tr>
				<td><input type="submit" id="btn" class="fl_l" value="Submit" /></td>
			</tr>
		</table>

	</form>

<!--   <form method="get" action="admin/csvie/"  >
--> 

<!--     <form name="compose" enctype="multipart/form-data" action="<?php echo $this->baseUrl ?>csvie//" method="post">
     <table cellspacing="0" cellpadding="0" class="display">
     <thead>
    <tr>
   <td> <?php echo $this->translate('Products Export');?> </td>
   </tr>
   </thead>
   <tbody>
   <tr> <td> 
   <input name="searchfield" type="text" size="45" />
<input type="submit" value="Search" /> 
  </td></tr>
   </tbody>
   </table>
   </form> -->
   
   <?php if($this->pagination) { ?>
                                 <br />
<div class="fleft">
                                 <?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
                                 </div>
                                 <div class="pagination fright">
                                 <?php echo $this->pagination;?>
                                 </div>
                                 <div class="clear"></div>
                                 <?php } ?>

<script type="text/javascript"> 
   // <![CDATA[
   $(document).ready(function() {       
       $('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
          e.preventDefault();
          var parent = $(this).parents('tr');
          $.ajax({
            type: 'post',
                url: "?module=banners&controller=admin&action=delete",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                parent.animate({
                  'backgroundColor': '#FFBFBF'
                      }, 400);
              },
                success: function () {
                parent.fadeOut(400, function () {
                    parent.remove();
                  });
              }
            });
        }
         });
});
// ]]>
</script>

 <?php
if($_SERVER['REQUEST_METHOD'] == "POST") {
 function exportCSV() {
	$host = 'localhost'; // MYSQL database host adress
	$user = 'root'; // Mysql Datbase user
	$pass = 'root'; // Mysql Datbase password
	$con = mysql_connect($host, $user, $pass);
    
    if (!$con) {
      die('Could not connectss: ' . mysql_error());
    }

    //change databse name here 
    $db = 'upload';
    //mysql-connection 
    mysql_select_db("$db", $con);
    $getTable = "SELECT a.sku,a.vsku,a3.name  AS product_tags_name,a.title  AS product_name ,a.description  AS product_description,a.price  AS product_price,a.procesing_unit,a12.title AS shop_name,a14.iso2 AS ship_from_country,
a8.picture  AS product_pic_name,a15.title AS Category_title,a1.quantity AS product_quantity,a16.title AS section_name 
FROM item a
LEFT JOIN item_quantity a1 ON a.id = a1.item
LEFT JOIN item_tag  a2 ON a.id = a2.item
LEFT JOIN tags a3 ON a2.tag = a3.id
LEFT JOIN item_picture_to_color a6 ON a.id = a6.item
LEFT JOIN item_picture a7 ON a.id = a7.item
LEFT JOIN picture a8 ON a6.picture = a8.id
LEFT JOIN itemtype_description a9 ON a.id = a2.item
LEFT JOIN item_in_treasury a10 ON a.id = a10.item
LEFT JOIN users_treasury a11 ON a10.treasury_id = a11.treasury_id
LEFT JOIN shops a12 ON a.shop_id = a12.shop_id
LEFT JOIN category a13 ON a.category = a13.category_id
LEFT JOIN countries a14 ON a.ship_from_country = a14.country_id
LEFT JOIN category_description a15 ON a.category = a15.category_id
LEFT JOIN shops_section a16 ON  a.shop_section = a16.section_id
WHERE 1
GROUP BY a.id DESC";
  echo $getTable;
    $table = mysql_query($getTable) or die ("Sql error : " . mysql_error());
    $exportCSV = fopen("/home/manish/public_html/test/export.csv", 'w');

    // fetch a row and write the column names out to the file
    $row = mysql_fetch_assoc($table);
    $line = "";
    $comma = "";
    foreach($row as $name => $value) {
      $line .= $comma . '"' . str_replace('"', '""', $name) . '"';
      $comma = "\t";
    }
    $line .= "\n";
    fputs($exportCSV, $line);

    // remove the result pointer back to the start
    mysql_data_seek($table, 0);

    // and loop through the actual data
    while($row = mysql_fetch_assoc($table)) {
      $line = "";
      $comma = "";
      foreach($row as $value) {
        $line .= $comma . '"' . str_replace('"', '""', $value) . '"';
        $comma = "\t";
      }
      $line .= "\n";
      fputs($exportCSV, $line);
    }
    fclose($exportCSV);

header('Location: http://localhost/test/export.csv');
exit;
       
  }
 exportCSV();
}
echo 'import-export Module by Manish';
?>
<?php echo $this->footer_part; ?>
